######################################################################
# Automatically generated by qmake (2.01a) sam. oct. 26 21:52:34 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += affichage.h
SOURCES += simulation.cpp affichage.cpp

QT += network
QT += widgets
